name: 🔨 Build scikit-decide doc

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build-docs:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Download Unix artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: wheels
      - name: Install scikit-decide 
        run: |
          ls -lrt
          pip install scikit-decide
      - name: Generate
        run: |
          (cd docs; python autodoc.py)
      - name: generate documentation
        run: yarn global add vuepress && yarn install && yarn docs:build && touch docs/.vuepress/dist/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.gh_access_token }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/.vuepress/dist # The folder the action should deploy.
          GIT_CONFIG_EMAIL: guillaume.alleon@gmail.com
          COMMIT_MESSAGE: publish documentation
          CLEAN: true
          SINGLE_COMMIT: true
